# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17070jW0OJzkkbwzOFUmZDu2nvUZxjaf9
"""

pip install streamlit -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dashboard.py
# import streamlit as st
# import matplotlib.pyplot as plt
# import numpy as np
# st.write(
#     """
#     PROYEK ANALISIS DATA ECOMMERCE-TUGAS AKHIR(BELAJAR ANALISIS DATA DENGAN PYTHON-DICODING)
# 
#     ANNISSA CLARYTA BERLIANA PUTRI (ML-58) [M009D4KX2794] MACHINE LEARNING PATH
#     """
# )
# st.markdown(
#         "<div style='display: flex; justify-content: center;'>"
#         "<img src=/barchart.png "
#         "width='200' style='border-radius: 50%;'>"
#         "</div>",
#         unsafe_allow_html=True
#     )
#

pip install pyngrok

from pyngrok import ngrok

!streamlit run dashboard.py & npx localtunnel --port 8501
